import React, { useState } from "react";
import DocumentResult from "../DocumentResult";
import PlaceholderModal from "../PlaceholderModal";
import { uploadTemplate } from "../../api";
import "../../styles/CircularForm.css";
const CircularForm = ({ onSubmit }) => {
  const [purpose, setPurpose] = useState("");
  const [eventName, setEventName] = useState("");
  const [date, setDate] = useState("");
  const [eventDetails, setEventDetails] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [downloaded, setDownloaded] = useState(false);
  const [uploadedTemplate, setUploadedTemplate] = useState(null);
  const [uploadLoading, setUploadLoading] = useState(false);

  const handleTemplateUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    
    setUploadLoading(true);
    try {
      const response = await uploadTemplate(file, "circular");
      setUploadedTemplate(response.filename);
      alert(`Template uploaded successfully: ${response.filename}`);
    } catch (err) {
      alert(`Upload failed: ${err.message}`);
    } finally {
      setUploadLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setDownloaded(false);
    const res = await onSubmit({
      docType: "circular",
      purpose,
      eventName,
      date,
      eventDetails,
      template: uploadedTemplate,
    });
    setResult(res);
    setLoading(false);
  };

  const handleDownload = () => {
    setDownloaded(true);
    setTimeout(() => {
      setResult(null);
      setDownloaded(false);
    }, 300);
  };

  const circularPlaceholders = [
    { name: "{{purpose}}", description: "Purpose of the circular" },
    { name: "{{event}}", description: "Name of the event" },
    { name: "{{date}}", description: "Date of the circular" },
    { name: "{{content}}", description: "Body content (automatically generated by AI)" },
  ];

  return (
    <form className="circular-form" onSubmit={handleSubmit}>
      <div style={{position: 'relative'}}>
        <PlaceholderModal placeholders={circularPlaceholders} title="Circular" />
        <h2>Generate Circular</h2>
      </div>

      <label>Upload Template (Word File) - Optional</label>
      <div style={{display: 'flex', gap: '0.5rem', alignItems: 'center'}}>
        <input
          type="file"
          accept=".docx"
          onChange={handleTemplateUpload}
          disabled={uploadLoading}
        />
        {uploadLoading && <span>Uploading...</span>}
        {uploadedTemplate && <span style={{color: '#00e5ff'}}>✓ {uploadedTemplate.split('/').pop()}</span>}
      </div>

      <label>Purpose</label>
      <input
        type="text"
        value={purpose}
        onChange={(e) => setPurpose(e.target.value)}
        placeholder="E.g., Instructions for students"
        required
      />

      <label>Event Name</label>
      <input
        type="text"
        value={eventName}
        onChange={(e) => setEventName(e.target.value)}
        required
      />

      <label>Date</label>
      <input
        type="date"
        value={date}
        onChange={(e) => setDate(e.target.value)}
        required
      />

      <label>Event Details</label>
      <textarea
        value={eventDetails}
        onChange={(e) => setEventDetails(e.target.value)}
        placeholder="Provide details/context for the circular"
      />

      <div className="button-row">
        {!loading && (!result || downloaded) && (
          <button type="submit" className="primary-btn">Generate</button>
        )}
        {loading && (
          <div className="loading-spinner small"></div>
        )}
        {!loading && result && !downloaded && (
          <DocumentResult result={result} onDownload={handleDownload} inline />
        )}
      </div>
    </form>
  );
};

export default CircularForm;