import React, { useState } from "react";
import DocumentResult from "../DocumentResult";
import PlaceholderModal from "../PlaceholderModal";
import { uploadTemplate } from "../../api";
import "../../styles/LetterForm.css";
const LetterFormNew = ({ onSubmit }) => {
  const [purpose, setPurpose] = useState("");
  const [eventDetails, setEventDetails] = useState("");
  const [sender_details,setSender_details]=useState("")
  const [recipient_details,setRecipient_details]=useState("")
  const today = new Date().toISOString().split("T")[0];
  const [date, setDate] = useState(today);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [downloaded, setDownloaded] = useState(false);
  const [uploadedTemplate, setUploadedTemplate] = useState(null);
  const [uploadLoading, setUploadLoading] = useState(false);

  const handleTemplateUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    
    setUploadLoading(true);
    try {
      const response = await uploadTemplate(file, "letter");
      setUploadedTemplate(response.filename);
      alert(`Template uploaded successfully: ${response.filename}`);
    } catch (err) {
      alert(`Upload failed: ${err.message}`);
    } finally {
      setUploadLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setDownloaded(false);
    const res = await onSubmit({
      docType: "letter",
      sender_details,
      recipient_details,
      date,
      purpose,
      eventDetails,
      template: uploadedTemplate,
    });
    setResult(res);
    setLoading(false);
  };

  const handleDownload = () => {
    setDownloaded(true);
    setTimeout(() => {
      setResult(null);
      setDownloaded(false);
    }, 300);
  };

  const letterPlaceholders = [
    { name: "{{sender_details}}", description: "Sender name, address, phone, email" },
    { name: "{{recipient_details}}", description: "Recipient name, address, phone, email" },
    { name: "{{date}}", description: "Date of the letter" },
    { name: "{{purpose}}", description: "Main purpose of the letter" },
    { name: "{{content}}", description: "Letter body content (automatically generated by AI)" },
  ];

  return (
    <form className="letter-form" onSubmit={handleSubmit}>
      <div style={{position: 'relative'}}>
        <PlaceholderModal placeholders={letterPlaceholders} title="Letter" />
        <h2>Generate Letter</h2>
      </div>

      <label>Upload Template (Word File) - Optional</label>
      <div style={{display: 'flex', gap: '0.5rem', alignItems: 'center'}}>
        <input
          type="file"
          accept=".docx"
          onChange={handleTemplateUpload}
          disabled={uploadLoading}
        />
        {uploadLoading && <span>Uploading...</span>}
        {uploadedTemplate && <span style={{color: '#00e5ff'}}>✓ {uploadedTemplate.split('/').pop()}</span>}
      </div>

      <label>Purpose</label>
      <textarea
        value={purpose}
        onChange={(e) => setPurpose(e.target.value)}
        placeholder="E.g., Invitation to seminar on AI"
        required
      />
      <label>Recipient Details</label>
      <textarea
        value={recipient_details}
        onChange={(e) => setRecipient_details(e.target.value)}
        placeholder="E.g., recipient name, address, phone number, email"
        required
      />
      <label>Sender Details</label>
      <textarea
        value={sender_details}
        onChange={(e) => setSender_details(e.target.value)}
        placeholder="E.g., sender name, address, phone number, email"
        required
      />
      <label>Date of letter</label>
      <input
        type="date"
        value={date}
        onChange={(e) => setDate(e.target.value)}
        required
      />
      <label>Event Details</label>
      <textarea
        value={eventDetails}
        onChange={(e) => setEventDetails(e.target.value)}
        placeholder="Provide context/details for the generated letter body"
      />
      <div className="button-row">
        {!loading && (!result || downloaded) && (
          <button type="submit" className="primary-btn">Generate</button>
        )}
        {loading && (
          <div className="loading-spinner small"></div>
        )}
        {!loading && result && !downloaded && (
          <DocumentResult result={result} onDownload={handleDownload} inline />
        )}
      </div>
    </form>
  );
};

export default LetterFormNew;